apiVersion: v1
kind: Secret

metadata:
  name: redemption-secret
  namespace: redemption

type: Opaque

stringData:

  DATABASE_USERNAME: admin

  DATABASE_PASSWORD: change-me-demo

  API_KEY: demo-api-key
